export const themes = [
	{
		name: "Blue",
		value: "theme-blue",
	},
	{
		name: "Dark",
		value: "theme-dark",
	},
];

export const sets = [
	"NS-01",
	"NS-02",
	"NS-03",
	"NS-04",
	"NS-05",
	"NS-06",
	"NS-07",
	"NS-08",
	"NS-02-M01",
	"NS-02-M02",
	"NS-02-M03",
	"NS-02-M04",
	"NS-02-M05",
	"NS-02-M06",
	"NS-02-M07",
	"NS-02-M08",
	"NS-05-M01",
	"NS-05-M02",
	"NS-05-M03",
	"NS-05-M04",
	"NS-05-M05",
	"NS-05-M06",
	"NS-10-M01",
	"NS-10-M02",
	"NS-10-M03",
	"NS-10-M04",
];

export const rarities = [
	"AR",
	"BGL",
	"BW",
	"CP",
	"DSR",
	"FR",
	"FSR",
	"GP",
	"JNH",
	"LP",
	"LP/99",
	"LSP",
	"MC",
	"MP",
	"MR",
	"MR",
	"MR/199",
	"NNS",
	"NTR",
	"PR",
	"PTR",
	"R",
	"SD",
	"SER",
	"SP",
	"SR",
	"SSP",
	"SSR",
	"UR",
	"UTR",
	"XNR",
	"XR",
	"XR",
	"ZR",
];

export const series = [
	"86",
	"A Certain Magical Index",
	"A Silent Voice",
	"Accel World",
	"Akame Ga Kill!",
	"Akashic Records Of Bastard Magic Instructor",
	"Akebi's Sailor Uniform",
	"Aldnoah.Zero",
	"Alice Gear Aegis",
	"Alya, Who Sits Next to Me, Sometimes Whispers Sweet Nothings in Russian",
	"Amagi Brilliant Park",
	"And you thought there is never a girl online?",
	"Angel Beats!",
	"Angels of Death",
	"Another",
	"Aria the Scarlet Ammo",
	"Arifureta: From Commonplace to World's Strongest",
	"Arknights",
	"Assault Lily: Bouquet",
	"Atelier Series",
	"Attack on Titan",
	"Azur Lane",
	"BanG Dream!",
	"Bayonetta",
	"Ben-To",
	"Berserk",
	"Beyond the Boundary",
	"Bishoujo Mangekyou",
	"Black Bullet",
	"Black Rock Shooter",
	"Bleach",
	"Blend S",
	"Bloom Into You",
	"Blue Archive",
	"Boarding School Juliet",
	"BOFURI: I Don't Want to Get Hurt, so I'll Max Out My Defense.",
	"Brynhildr in the Darkness",
	"Bungo Stray Dogs",
	"Burn the Witch",
	"Cardcaptor Sakura",
	"Celestial Method",
	"Cells at Work!",
	"Chainsaw Man",
	"Charlotte",
	"Chivalry of a Failed Knight",
	"Chobits",
	"Citrus",
	"Clannad",
	"Classroom of the Elite",
	"Code Geass",
	"Cyberpunk Edgerunners",
	"Dagashi Kashi",
	"Danganronpa",
	"Darker than Black",
	"Darling in the Franxx",
	"Date A Live",
	"Dead or Alive",
	"Death Note",
	"Demon Slayer",
	"Detective Conan",
	"D-Frag!",
	"Didn't I Say to Make My Abilities Average in the Next Life?!",
	"Digimon",
	"Do You Love Your Mom and Her Two-Hit Multi-Target Attacks?",
	"Dragonball",
	"Drakengard 3",
	"Dropkick on My Devil!",
	"Elden Ring",
	"ENDRO!",
	"Engage Kiss",
	"Eromanga Sensei",
	"Eternal City",
	"Eva",
	"Expelled from Paradise",
	"Fairy Tail",
	"Fate Series",
	"Final Fantasy",
	"Fire Force",
	"Flower Knight Girl",
	"Food Wars! Shokugeki no Soma",
	"Forever 7th Capital",
	"Fox Spirit Matchmaker",
	"Full Metal Panic!",
	"Fullmetal Alchemist",
	"Future Diary",
	"Gabriel DropOut",
	"GATE",
	"Genshin Impact",
	"Ghost In The Shell",
	"Gintama",
	"Girl Cafe Gun",
	"Girls' Frontline",
	"Girls Und Panzer",
	"Goblin Slayer",
	"God Eater",
	"God's Blessing on this Wonderful World!",
	"Golden Kamuy",
	"Gosick",
	"Granblue Fantasy",
	"Gray Raven",
	"Grimgar: Ashes and Illusions",
	"Grimoire of Zero",
	"Ground Control to Psychoelectric Girl",
	"Guilty Crown",
	"Gunbuster",
	"Gundam",
	"Gundam Build Divers Re:Rise",
	"Gurren Lagann",
	"Haganai: I don't have many friends",
	"Heaven's Lost Property",
	"Heavy Object",
	"Hell Girl",
	"Higehiro: After Being Rejected, I Shaved and Took in a High School Runaway",
	"High School DxD",
	"High School Of The Dead",
	"Himouto! Umaru-chan",
	"Hololive",
	"Honkai Impact",
	"Horimiya",
	"Horizon in the Middle of Nowhere",
	"How to Raise a Boring Girlfriend",
	"Hyouka",
	"Hyperdimension Neptunia",
	"If it's for My Daughter, I'd Even Defeat a Demon Lord",
	"In/Spectre",
	"Interspecies Reviewers",
	"Inuyasha",
	"Is It Wrong to Try to Pick Up Girls in a Dungeon?",
	"Is the Order a Rabbit?",
	"Is This a Zombie?",
	"Island",
	"I've Been Killing Slimes for 300 Years and Maxed Out My Level",
	"JoJo's Bizarre Adventure",
	"Jujutsu Kaisen",
	"K",
	"Kabaneri of the Iron Fortress",
	"Kaede Takagaki",
	"Kaguya-sama: Love is War",
	"Kaichou Wa Maid-Sama!",
	"Kakegurui",
	"Kakushigoto",
	"Kantai Collection",
	"Kara no Kyoukai",
	"Katana Maidens: Toji no Miko",
	"Katanagatari",
	"Kemono Michi: Rise Up",
	"Kiki's Delivery Service",
	"Kill la Kill",
	"Kiniro Mosaic",
	"Komi Can't Communicate",
	"K-On!",
	"Lagrange: The Flower of Rin-ne",
	"Laid-Back Camp",
	"Land of the Lustrous",
	"League of Legends",
	"Legend of Zelda",
	"Liar Liar",
	"Little Witch Academia",
	"Love Live!",
	"Love, Chunibyo & Other Delusions!",
	"Lucky Star",
	"Lycoris Recoil",
	"Macross",
	"Magical Girl Lyrical Nanoha",
	"Mahjong Soul",
	"Masamune-kun's Revenge",
	"Mayoi Neko Overrun!",
	"Mekuiro",
	"Metal Gear Solid",
	"Metroid",
	"Minna Atsumare! Falcom Gakuen SC",
	"Miss Kobayashi's Dragon Maid",
	"Mobile Suit Gundam: The Witch from Mercury",
	"Monogatari Series",
	"Monthly Girl's Nozaki-kun",
	"Ms. vampire who lives in my neighborhood",
	"Muse Dash",
	"Mushoku Tensei: Jobless Reincarnation",
	"My Dress-Up Darling",
	"My Hero Academia",
	"My Mental Choices Are Completely Interfering With My School Romantic Comedy",
	"My Next Life as A Villainness",
	"My Youth Romantic Comedy Is Wrong As I Expected",
	"Nagi-Asu: A Lull in the Sea",
	"Naruto",
	"Needy Streamer Overload",
	"Nekopara",
	"New Game!",
	"NieR: Automata",
	"NIKKE: The Goddess Of Victory",
	"Nisekoi: Fake Love",
	"No Game No Life",
	"Noragami",
	"Nurse Witch Komugi-chan R",
	"Nyaruko: Crawling with Love!",
	"One Piece",
	"One Punch Man",
	"Onmyoji",
	"OreImo",
	"Oreshura",
	"Our Last Crusade or the Rise of a New World",
	"Outbreak Company",
	"Overlord",
	"Overwatch",
	"Panty & Stocking with Garterbelt",
	"Persona",
	"Plastic Memories",
	"Pokemon",
	"Pretty Cure",
	"Princess Connect Re:Dive",
	"Princess Principal",
	"Problem Children Are Coming from Another World, Aren't They?",
	"Project SEKAI",
	"Psycho-Pass",
	"Puella Magi Madoka Magica",
	"Puella Magi Suzune Magica",
	"Punishing: Gray Raven",
	"Rance",
	"Rascal Does Not Dream of Bunny Girl Senpai",
	"Re:CREATORS",
	"Re:Zero",
	"Red:Pride of Eden",
	"Rent-a-Girlfriend",
	"Resident Evil",
	"Revue Starlight",
	"Rewrite",
	"Ro-Kyu-Bu!",
	"Rosario + Vampire",
	"Rozen Maiden",
	"Rurouni Kenshin",
	"RWBY",
	"Sailor Moon",
	"Saint Seiya",
	"Saint Tail",
	"Saki",
	"Sakura Wars",
	"School Days",
	"School-Live!",
	"Sekiro",
	"Senki Zesshō Symphogear",
	"Senren Banka",
	"Seraph of The End",
	"Shadows House",
	"Shakugan no Shana",
	"Shikimori's Not Just a Cutie",
	"Shin Chuuka Ichiban!",
	"Shugo Chara!",
	"Sky of Connection",
	"Sleepy Princess in the Demon Castle",
	"Slow Start",
	"So I'm a Spider, So What?",
	"Sound! Euphonium",
	"Spice & Wolf",
	"Spice and Wolf",
	"Spy X Family",
	"SSSS.DYNAZENON",
	"SSSS.GRIDMAN",
	"Starcraft II",
	"Steins; Gate",
	"Street Fighter",
	"Strike the Blood",
	"Strike Witches",
	"Summer Pockets",
	"Summer Time Rendering",
	"Summon the Beasts",
	"Super Mario",
	"Suzume No Tojimari",
	"Sword Art Online",
	"Tada Never Falls in Love",
	"Takt Op. Destiny",
	"Tamako Market",
	"Teasing Master Takagi-san",
	"That Time I Got Reincarnated as a Slime",
	"The 'Hentai' Prince and the Stony Cat",
	"The Ancient Magus' Bride: Those Awaiting a Star",
	"The Angel Next Door Spoils Me Rotten",
	"The Aquatope on White Sand",
	"The Beast Tamer Who Got Kicked Out From His Party Meets a Cat Girl From the Superior Race",
	"The Day I Became a God",
	"The Demon Girl Next Door",
	"The Detective is Already Dead",
	"The Disastrous Life of Saiki K",
	"The Dungeon of Black Company",
	"The Familiar of Zero",
	"The Flower We Saw That Day",
	"The Garden of Sinners",
	"The Genius Prince's Guide to Raising a Nation Out of Debt",
	"The Hero is Overpowered but Overly Cautious",
	"The Idolm@ster",
	"The Irregular at Magic High School",
	"The Journey of Elaina",
	"The King of Fighters",
	"The Last of Us",
	"The Legend of Heroes: Kuro no Kiseki",
	"The Legend of Heroes: Trails of Cold Steel",
	"The Legend of Sword and Fairy (Chinese Paladin)",
	"The Melancholy of Haruhi Suzumiya",
	"The Misfit of Demon King Academy",
	"The Outcast",
	"The Pet Girl of Sakurasou",
	"The Quintessential Quintuplets",
	"The Rising of the Shield Hero",
	"The Ryuo's Work is Never Done",
	"The Seven Deadly Sins",
	"The Witcher",
	"The World's Finest Assassin Gets Reincarnated in Another World as an Aristocrat",
	"To LOVE-Ru",
	"Toaru Kagaku no Railgun",
	"Toilet-bound Hanako-kun",
	"Tokyo Ghoul",
	"Tokyo Ravens",
	"Tomb Raider",
	"TONIKAWA: Over the Moon For You",
	"Toradora",
	"Touhou Project",
	"Tsukihime",
	"Tsuredure Children",
	"Uma Musume Pretty Derby",
	"Unbreakable Machine-Doll",
	"Uncle from Another World",
	"Urara Meirochou",
	"Utawarerumono",
	"Violet Evergarden",
	"Vivy -Fluorite Eye's Song-",
	"Vocaloid",
	"VSinger",
	"VTuber",
	"Wandering Witch: The Journey of Elaina",
	"Warship Girls R",
	"Wasteful Days of High School Girls",
	"WATATEN!: An Angel Flow Down to Me",
	"We Never Learn!: Bokuben",
	"Weathering with You",
	"Welcome to Demon School! Iruma-kun",
	"When Supernatural Battles Became Commonplace",
	"When they Cry",
	"White Album 2",
	"Wonder Egg Priority",
	"Working!!",
	"World of Warcraft",
	"WorldEnd: What do you do at the end of the world? Are you busy? Will you save us?",
	"Xenoblade",
	"Ya Boy Kongming!",
	"Yosuga no Sora",
	"You and Me and Her",
	"Your Lie in April",
	"Your Name",
	"Yu-Gi-Oh!",
	"YuruYuri: Happy Go Lily",
	"Yuuki Yuuna is a Hero",
	"YuYu Hakusho",
	"Zombieland Saga",
];
